heroku/logplex

src/logplex.app.src
src/logplex_http_drain.erl
src/logplex_utils.erl
test/logplex_http_drain_SUITE.erl
upgrades/v78_v79/live_upgrade.erl

When a drain is disconnected it currently takes at least 1 full seconds before the connection is re-established. For a high volume drain, this will almost guarantee log loss as the short buffer will be rapidly filled up. This branch attempts to resolve that behaviour by removing the forced hibernate and implementing an exponential backoff on re-connect behaviour.

Drain performance

---

src/logplex_http_drain.erl
upgrades/v79_v80/live_upgrade.erl

Monitoring of the logplex cluster revealed that post this change set the
binary memory usage climbed. IMO this doesn't make sense because the
drain buffer process will still retain references to any binaries
cleaned up by forcing a hibernate here. But, graphs do not lie. This
commit reverts the changes in an attempt to reclaim that binary memory.
For reference this original commit that converted these
b551562

Revert https hibernate changes

---

src/logplex_api.erl
upgrades/v80_v81/live_upgrade.erl

This PR fixes a number of issues related to tail sessions.
Firstly, when a session is created and logplex is aware of the api endpoint url, it should return full urls instead of just a relative path.
Secondly, when shipping logs out to tail sessions through an ELB the ELB would interpret the HTTP reply as invalid HTTP and return a 502 - Bad Gateway. The log shipping has been updated to use a chunked HTTP reply instead of appending data directly to the socket. Thus fixing the ELBs issue with the HTTP reply and resolving the 502 error.

Tail session fixes

---

src/logplex_logs_rest.erl
src/logplex_message.erl
src/logplex_worker.erl

Use a counter to track unknown tokens that appear in syslog and http
interfaces (including anychan).

track unknown tokens in folsom metrics

---

doc/schema/deprecated.md
doc/schema/schema.json
doc/schema/schema.md
doc/schema/schemata/session.yaml

* Documented some more deprecated API calls still in use.
* Added a missing title attribute that is required in order to generate clients using heroics

Further schema updates

---

README.md
src/logplex_api.erl
test/logplex_api_SUITE.erl

`POST /sessions` and `GET /sessions/{id}` currently require a `srv` query parameter which is a vestige of how logplex's load balancing setup used to work. Now it's just an extra hurdle for clients.

Remove old and unnecessary srv parameter.

---

.travis.yml
src/logplex_firehose.erl
src/logplex_realtime.erl
test/logplex_firehose_SUITE.erl

Add additional metrics around firehose channel posts. The metrics are per firehose shard. This allows for historical tracking of firehose usage and potential monitoring around post/sec to the shards.

record firehose posts into realtime metrics

---

doc/schema/schema.json
doc/schema/schema.md
doc/schema/schemata/health.yaml
src/logplex_api.erl
src/nsync_callback.erl

It is now possible to use the redis config master to synchronize API
read_only control rods via nsync. To flag the API into read_only mode
use
```
SETBIT control_rod 0 1
```
to put the API back into normal operation use:
```
SETBIT control_rod 0 0
```

Nsync control rods

---

.travis.yml
.travis/install_compose.sh
Dockerfile
Makefile
docker-compose.yml

This docker-compose configuration isolates the deps and ebin directories
into a base image. This base image is run as a data volume by the
logplex service and a new compile service.
```
docker-compose run compile
```
can be used to quickly rebuild the logplex source. To recompile
everything from scratch (including deps) use:
```
docker-compose run compile make all
```
The `Makefile` was added as a workaround to some kind of pseudo-tty bug
with rebar. Running the `rebar compile skip_deps=true` commands directly
Wwould result in rebar hanging. The inclusion of the `Makefile` or some
bash script to execute fixes that issue.
The next task will be to create docker-compose service that connects an
eshell to a running logplex service.

Docker compile

---

bin/toggle_read_only

This script will allow us to toggle read only mode instead of having to interactively toggle it from within eshell.

Add script to toggle read only mode.

---

Dockerfile
docker-compose.yml
src/logplex_api.erl
src/logplex_tcpsyslog_drain.erl
src/logplex_tlssyslog_drain.erl
src/nsync_callback.erl
test/drain_test_protocol.erl
test/logplex_syslog_drain_SUITE.erl

Prior to this commit updates made using `/v2/channels/CHANNEL_ID/drains/DRAIN_ID` would update config redis and ETS on all clustered logplex nodes, but the `{error, {already_started, Pid}}` message was ignored. This meant that the updated drain URL would not take effect until after the logplex node had been restarted.
This isn't an ideal solution, since some loss could still occur. However, it is a quick fix until a more ideal in-place update can be made. Further refactoring of the drain FSMs will be required for that to take place.

Fixes drain update logic

---

src/logplex_drain.erl
src/logplex_tls.erl
src/logplex_tlssyslog_drain.erl
test/logplex_syslog_drain_SUITE.erl

Configuration is done as part of the drain URI, for example:
syslog+tls://myserver.com:8583/#insecure=true
Values other than "true" to the "insecure" URI fragment are implicitly treated
as a False.

Implement noverify opt out for TLS syslog drains

---

src/logplex.app.src
src/logplex_app.erl
src/logplex_tls.erl

Adds support for pinned certificates using the `partial_chain/1` hooks available to newer versions of Erlang. If pinning is not desired simply do not set the `LOGPLEX_TLS_PINNED_CERTFILE` environment variable or point it to an empty file.
Two new environment variables have been added to help customize the location of various certificate files.
`LOGPLEX_TLS_CACERTFILE` - the Root CA bundle in PEM format
`LOGPLEX_TLS_PINNED_CERTFILE` - the pinned certificate bundle in PEM format

support for pinned certificates

---

src/logplex.app.src
src/logplex_app.erl
src/logplex_tls.erl
test/logplex_syslog_drain_SUITE.erl

Adds the ability to pin certificates via the `LOGPLEX_TLS_PINNED_CERTS`
OS environment variable. Logplex expects this variable to contain PEM
formatted certificates. The presence of this new variable supercedes any
file referenced by the `LOGPLEX_TLS_PINNED_CERTFILE` variable.
The certificates are processed and cached in DER format internally.

support for pinning certs via OS var directly

---

src/logplex.app.src
src/logplex_tls.erl

TLS 1.0 is considered an early TLS, and is over 15 years old. PCI will
prohibit the use of 1.0 after June 2016.
This just sets some good patterns in place early on

restrict TLS to 1.2 or 1.l

---

src/logplex_api.erl

The /v2/channels/$channelId/drains endpoint now returns 404 if a channel ID
does not exist.

Don't create drains on non-existant channels

---

src/logplex_drain_buffer.erl
src/logplex_http_drain.erl
test/logplex_http_drain_SUITE.erl

Fixes a bug that causes the buffers to shrink if the connection immediately fails after the drain has idled out

HTTP idle fix

---

src/logplex.app.src
src/logplex_http_drain.erl
test/logplex_http_drain_SUITE.erl

Addresses a few issues for low volume drains where the connecting
endpoint has closed the connection.
1. New logs could arrive after 5 minutes, but before the idle timeout
fuzz padding. The buffer would be immediately shrunk, when the send
fails.
2. Logs that failed to send, won't be retried until more logs enter the
drain, if the other end has closed the connection those re-framed logs
are lost after a single retry.
3. If the drain is in a disconnected state, the last known successfully
sent time isn't cleared when the idle timeout triggers.

don't track idle time towards buffer shrinking

---

src/logplex.app.src
src/logplex_http_drain.erl

Set to 2.4mins, along with inconsistency fixes and refactoring.
/cc @voidlock

Adjust http drain idle timeout

---

Dockerfile
README.md
docker-compose.yml

I've been bitten by this nearly every time. Finally have working instructions in README to do docker-based development.
Use the compile compose command to compile sources using volumes; the same
volumes to be used for the (renamed) `logplex_console` command.
@voidlock please review.

Working docker workflow for local edit-compile-run cycle

---

src/logplex_http_drain.erl
src/logplex_message.erl
test/logplex_http_drain_SUITE.erl
test/logplex_syslog_drain_SUITE.erl

A revival of an older 429 retry branch. This will have no effect for drains that hit their daily quota. The main goal of this change is to cope better when a drain spikes temporarily and get rate limited for a short period of time.

retry http 429 responses

---

rebar.lock

Merging the v97.fixes branch that pins nsync to a version that pins its dependencies.

Merge v97 fixes

---

relx.config

This reverts commit edfc88cb2473fb0d6897fcf12410f9b357c6badd.
Switching to semver caused some internal deployment pain that I would rather punt on for now.

Revert "configure semver releases"

---

doc/schema/schema.json
doc/schema/schema.md
doc/schema/schemata/channel.yaml
doc/schema/schemata/drain.yaml
doc/schema/schemata/session.yaml
doc/schema/schemata/token.yaml

Proposal for logplex v3 api. Objective is to ensure core-services holds control over channel ids to mitigate race conditions during channel creation. The proposed api aimes to:
* Leave v2 api completely intact
* Deprecate v2
* Add new v3 api endpoints using the new channel identifiers where necessary
See also https://github.com/heroku/cedar-ops/issues/122

Proposal for v3 api

---

src/logplex_api_v3_healthcheck.erl
test/logplex_api_v3_SUITE.erl

Code for the healtcheck was adapted from an unused part of the old API. Now uses the same pattern for the v3 API as the logs API.
cc @voidlock

Simplify v3 healthcheck

---

doc/schema/schema.json
doc/schema/schema.md
doc/schema/schemata/session.yaml
src/logplex_api_v3_sessions.erl
test/logplex_api_v3_SUITE.erl

For consistency we implement the v3 API sessions endpoint which is equivalent to the v2 version. 
One minor difference between v3 and v2 is that the channel for which the session is created must exist, otherwise we return a `422 Unprocessable Entity`.

Implement sessions endpoint

---

src/logplex.app.src
src/logplex_app.erl
src/logplex_logs_rest.erl
test/logplex_api_v3_SUITE.erl
test/logplex_logs_rest_SUITE.erl

We need to ensure the API URLs for v2 and v3 API are configured. The v3
API requires them in order to redirect a client with a full URL. The v2 API
would return only a path without a hostname. Note this may change how a client
handles redirects.
The new default sets them to:
* v2: `http://localhost:8001`
* v3: `http://localhost:8002`
The environment variables `LOGPLEX_API_ENDPOINT_URL` and
`LOGPLEX_HTTP_V3_URL` are now required to be set, otherwise the above
mentioned defaults are returned.

Require API URLs

---

src/logplex_api_v3_sessions.erl
test/logplex_api_v3_SUITE.erl

Session creation for the v3 API was broken because the request body was not stored properly. It would store an empty binary which then breaks fetching the session. This problem is now fixed.

Fix v3 session creation

---

bin/redgrid

When `redgrid:reload_config` is called it first checks to see if
`redis_url` is set in the application env. If not present, it will
reload from `os:getenv`. However, since the VM hasn't been reloaded the
new env vars still won't be picked up.
This works around the issue by directly updating the application env
var, before calling `reload_config`.
Also see, https://github.com/heroku/redgrid/blob/logplex/src/redgrid.erl#L55-L61

work around reloading redis options from new env

---

src/logplex.app.src
src/logplex_app.erl
src/logplex_logs_rest.erl

For https://salesforce.quip.com/LHvNARc4cIJ4
It seems like we are hitting either the acceptor pool size of 100 or the default ranch max connections limit of 1024. Make them tunable, defaulting to their current values, so we can verify.

 make http log input acceptors and max connections tunable

---

src/logplex_api_v3_sessions.erl
src/logplex_app.erl
test/logplex_api_v3_SUITE.erl

New environment variable `DENY_TAIL_SESSIONS` allows to block creation
of tail sessions.

Add control rod to deny creation of tail sessions

---

src/logplex_app.erl
src/logplex_message.erl

New environment variable DENY_REDIS_BUFFERS to stop storing logs in
redis overall. The value must be set to `no_redis` in order deny redis
buffers.

Add control rod to deny redis buffers

---

src/logplex_message.erl

This makes the control rod consistent with all other control rods. It
should be a boolean rather than `no_redis`.

tweaks the deny_redis_buffers control rod

---

src/logplex_app.erl
src/logplex_message.erl

Setting the `DISABLE_DRAIN_FORWARDING` env var to `true` will stop all
forwarding to drains. Setting the `deny_drain_forwarding` application
var on a running system to instantly kill all new traffic to drains.
Drains will still continue to send any data that has been buffered until
the buffers are cleared out.

control rod to stop drain forwarding

---

src/logplex_app.erl

New environment variable DISABLE_FIREHOSE disables the firehose on
startup when set to true.

Add control rod for firehose

---

src/logplex_app.erl
src/logplex_logs_rest.erl
test/logplex_logs_rest_SUITE.erl

New environment variable DENY_LOGS_INGRESS. When set to "true" the logs
endpoint return 503 Service Unavailable for all requests.

Add control rod for logs ingress

---

bin/redgrid

Adds a live control rod to disable clustering.
The operator can simply run `bin/redgrid stop` to disable redgrid and force Logplex to drop all connections to remote hosts. This action can be undone by executing `bin/redgrid resume`.

Live redgrid conrol rod

---

src/logplex_control_rods.erl

Reading config values without default errors out with missing config variable hence we want to see default here.

Fix control rod status poller defaults

---

src/logplex_api_v3.erl
src/logplex_api_v3_channel_logs.erl
test/logplex_api_SUITE.erl
test/logplex_api_v3_SUITE.erl

This new v3 API endpoint allows to fetch all buffered logs of a channel at once. 
* impelment new endpoint `v3/channels/:id/logs`
* test new endpoint

Implement endpoint for channel logs

---

Dockerfile

Will maybe cut down on errors I'm seeing as part of testing #222.

Dockerfile: fetch released rebar3 instead of building

---

src/logplex.app.src

As part of log-tails, there might be apps with 5 drains already, and we wouldn't be able to add the log-tails required drain there.
We'll need to increase this limit to 6. API still maintains `limit=5` so we're good on the public facing front.

increase drain limit to 6 from 5

---

src/logplex_ranch_metrics.erl
src/logplex_sup.erl

Emits connection counts for logplex_logs_rest and logplex_api_v3.
Mostly copied from #220

add logplex_ranch_metrics

---

src/logplex_api.erl
src/logplex_api_v3.erl
src/logplex_app.erl
src/logplex_control_rods.erl

When we split the status handling of v3 and legacy API control rods were measuring only legacy status. Now we only measure v3 API status. Legacy API is deprecated and won't need to be checked.

Fix v3 API status handling

---

src/logplex_shard.erl

There was a mismatch here when reconnects run out of retries and `{error, out_of_retries}` would be returned for `NewPid` which would end up in the reader map. This change ensures a connection was established within 5 minutes. If this retry period is exhausted the entire process crashes and would attempt to re-establish all (reader and writer) connections after a supervisor restart.

Fix redis read reconnects

---

src/logplex_queue.erl
src/logplex_redis_writer.erl
src/logplex_sup.erl
src/logplex_worker_sup.erl

The redis writers connectivity appears unreliable.
* extend redis writer restart intensity to 15000 restarts within 30 seconds 
* add some housekeeping for redis writers in logplex_queue
* don't let the writer exit normally on unexpected responses from a logplex_queue process
The prior restart intensity of the redis writer supervisor configuration did allow for 1000 restarts per 1 second. This is problematic for restarting redis writers, for example, when there are 100 shards and 10 writers per shard. On a network connectivity problem the number of restarts gets easily exceeded which forces a redis writer supervisor restart. After a supervisor restart all prior created connection information is lost. Without manual intervention the connection information is not automatically recovered. …

Adjust redis writer restart intensity

---

src/logplex_sup.erl

The logplex supervisor was still starting a redgrid process without checking if redgrid was enabled. This is now fixed.

Avoid regrid supervisor start when redgrid is disabled

---

src/logplex_http_drain.erl

Was trying to help answer a question about how logplex do today and
I noticed that we were missing the 429 case in this note.
Slack Chat: https://heroku.slack.com/archives/C2LA11J4S/p1543340768685200

docs: Add 429 mention in `handle_response_status` docs.

---

config/vm.args
rebar.config
rebar.lock
relx.config
src/logplex_api_v3_channel_logs.erl
src/logplex_api_v3_channels.erl
src/logplex_api_v3_drains.erl

With this change in place timeout errors are captured and will return a 500 error. This
doesn't change the overall behaviour as the client sees things, however it prevents
a process crash in Logplex.

Captures timeouts when looking up resources.

---

bin/control_rods
src/logplex.app.src
src/logplex_api.erl
src/logplex_api_v3.erl
src/logplex_app.erl
src/logplex_cred.erl
src/logplex_logs_rest.erl

This PR introduces a new Logplex app config `log_api_user` that when set to `true` (defaults: `false`) will log the credential id and user agent for any request to the API.
* Introduced `log_api_user` and `LOG_AP_USER` app config.
* Updated and refactored `bin/control_rods` to include new config.
* Added additional logging of the `cred_id` and user agent when `log_api_user` is set to `true`.
The app config can be set via the `LOG_API_USER` os environment variable or on an already running Logplex instance via the control rod. `./bin/control_rods enable_log_api_user`.
When Logplex is configured to log user access the v3 API will output log lines like the following
```
pid=<0.1127.0> m=logplex_api_v3 ln=288 class=info at=is_authorized request_id=edceb1f1-fd97-4957-ae1b-0cc289b9787c …
```

API User Access logging
